### ISSUE TITLE
Heroku app down?

### ISSUE THREAD

**Issue by luc-pitipuis** [cantrellnm/waniconjugation#3]
Hi,

when i try to submit my API key, i get a 503 error, it there an issue ? 

Also, should i use an api v2 key or the old one?

**Comment by cantrellnm** [comment]
@luc-pitipuis Thanks for bringing this to my attention, it looks like WaniKani shut down v1 of their API at the beginning of this month so I needed to make some changes to be compatible with v2.

Should be fixed now when using a v2 token! (I don't know for sure but doubt a v1 token would work.)
